// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abvbxvdqvkxuyirhjneo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFidmJ4dmRxdmt4dXlpcmhqbmVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NjIzNzAsImV4cCI6MjA2MzIzODM3MH0.SGb7Ot0AexYbwak72kCctNtLtEuBCnqp8RsrY6N33bk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);